<?xml version="1.0" encoding="utf-8"?><Database Name="Eres" Class="EresDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=Eres;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ERES.Net.Properties.Settings" SettingsPropertyName="EresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Grades" Member="Grades">
    <Type Name="Grade">
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RealisationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxValue" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Grade_GradeValue" Member="GradeValues" ThisKey="GradeID" OtherKey="GradeID" Type="GradeValue" />
      <Association Name="Realisation_Grade" Member="Realisation" ThisKey="RealisationID" OtherKey="RealisationID" Type="Realisation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GradeValues" Member="GradeValues">
    <Type Name="GradeValue">
      <Column Name="GradeValueID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GradeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Grade_GradeValue" Member="Grade" ThisKey="GradeID" OtherKey="GradeID" Type="Grade" IsForeignKey="true" />
      <Association Name="Registration_GradeValue" Member="Registration" ThisKey="RegistrationID" OtherKey="RegistrationID" Type="Registration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Group_Student" Member="Students" ThisKey="GroupID" OtherKey="GroupID" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Realisations" Member="Realisations">
    <Type Name="Realisation">
      <Column Name="RealisationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SemesterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Realisation_Grade" Member="Grades" ThisKey="RealisationID" OtherKey="RealisationID" Type="Grade" />
      <Association Name="Realisation_Registration" Member="Registrations" ThisKey="RealisationID" OtherKey="RealisationID" Type="Registration" />
      <Association Name="Semester_Realisation" Member="Semester" ThisKey="SemesterID" OtherKey="SemesterID" Type="Semester" IsForeignKey="true" />
      <Association Name="Subject_Realisation" Member="Subject" ThisKey="SubjectID" OtherKey="SubjectID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Registrations" Member="Registrations">
    <Type Name="Registration">
      <Column Name="RegistrationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RealisationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Registration_GradeValue" Member="GradeValues" ThisKey="RegistrationID" OtherKey="RegistrationID" Type="GradeValue" />
      <Association Name="Realisation_Registration" Member="Realisation" ThisKey="RealisationID" OtherKey="RealisationID" Type="Realisation" IsForeignKey="true" />
      <Association Name="Student_Registration" Member="Student" ThisKey="StudentID" OtherKey="StudentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Semesters" Member="Semesters">
    <Type Name="Semester">
      <Column Name="SemesterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Semester_Realisation" Member="Realisations" ThisKey="SemesterID" OtherKey="SemesterID" Type="Realisation" />
    </Type>
  </Table>
  <Table Name="dbo.Students" Member="Students">
    <Type Name="Student">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IndexNo" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Student_Registration" Member="Registrations" ThisKey="StudentID" OtherKey="StudentID" Type="Registration" />
      <Association Name="Group_Student" Member="Group" ThisKey="GroupID" OtherKey="GroupID" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subjects" Member="Subjects">
    <Type Name="Subject">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Conspect" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="url" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TimeStamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Subject_Realisation" Member="Realisations" ThisKey="SubjectID" OtherKey="SubjectID" Type="Realisation" />
    </Type>
  </Table>
</Database>